// Generated by CoffeeScript 1.8.0
(function() {
  var Bitmap, bitmap, pixel, render, setPixel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  setPixel = function(imageData, x, y, r, g, b, a) {
    var index;
    index = (x + y * imageData.width) * 4;
    imageData.data[index + 0] = r;
    imageData.data[index + 1] = g;
    imageData.data[index + 2] = b;
    return imageData.data[index + 3] = a;
  };

  render = function(element, bitmap) {
    var canvas, imageData, _i, _ref, _results;
    element.width = bitmap.width;
    element.height = bitmap.height;
    canvas = element.getContext("2d");
    imageData = canvas.createImageData(bitmap.width, bitmap.height);
    (function() {
      _results = [];
      for (var _i = 0, _ref = bitmap.width - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).map(function(i) {
      var _i, _ref, _results;
      return (function() {
        _results = [];
        for (var _i = 0, _ref = bitmap.height - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this).map(function(j) {
        var c;
        c = bitmap.data[i][j];
        return setPixel(imageData, i, j, c.r, c.g, c.b, 0xff);
      });
    });
    return canvas.putImageData(imageData, 0, 0);
  };

  pixel = function(r, g, b) {
    var c;
    c = {};
    c.r = r;
    c.g = g;
    c.b = b;
    return c;
  };

  bitmap = function(w, h) {
    var _i, _results;
    return (function() {
      _results = [];
      for (var _i = 1; 1 <= w ? _i <= w : _i >= w; 1 <= w ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).map(function() {
      var _i, _results;
      return (function() {
        _results = [];
        for (var _i = 1; 1 <= h ? _i <= h : _i >= h; 1 <= h ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this).map(function() {
        return pixel(0, 0, 0);
      });
    });
  };

  Bitmap = (function() {
    function Bitmap(width, height) {
      this.width = width;
      this.height = height;
      this.data = bitmap(this.width, this.height);
    }

    Bitmap.prototype.set = function(x, y, c) {
      return this.data[x][y] = c;
    };

    Bitmap.prototype.bold = function(d) {
      var bmp, rep;
      rep = function(a) {
        return [].concat.apply([], a.map(function(x) {
          var _i, _results;
          return (function() {
            _results = [];
            for (var _i = 1; 1 <= d ? _i <= d : _i >= d; 1 <= d ? _i++ : _i--){ _results.push(_i); }
            return _results;
          }).apply(this).map(function() {
            return x;
          });
        }));
      };
      bmp = new Bitmap(d * this.width, d * this.height);
      bmp.data = rep(this.data.map(rep));
      return bmp;
    };

    Bitmap.prototype.render = render;

    Bitmap.prototype.pixel = pixel;

    return Bitmap;

  })();

  Window.Bitmap = (function(_super) {
    __extends(Bitmap, _super);

    function Bitmap() {
      return Bitmap.__super__.constructor.apply(this, arguments);
    }

    return Bitmap;

  })(Bitmap);

}).call(this);
