// Generated by CoffeeScript 1.8.0
(function() {
  var App, board2bitmap, main;

  board2bitmap = function(board) {
    var bmp, _i, _ref, _results;
    bmp = new Window.Bitmap(board.width, board.height);
    (function() {
      _results = [];
      for (var _i = 0, _ref = board.width - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).map(function(i) {
      var _i, _ref, _results;
      return (function() {
        _results = [];
        for (var _i = 0, _ref = board.height - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this).map(function(j) {
        var c;
        c = bmp.pixel(0xff, (board.board[i][j] ? 0x00 : 0xf3), 0xff);
        return bmp.set(i, j, c);
      });
    });
    return bmp.bold(10);
  };

  App = (function() {
    function App() {
      var board;
      board = new Window.Board(11, 11);
      [4, 5, 6].map(function(i) {
        return [4, 5, 6].map(function(j) {
          return board.board[i][j] = true;
        });
      });
      board.board[5][5] = false;
      board.board[5][6] = false;
      this.board = board;
    }

    App.prototype.next = function() {
      return this.board.next();
    };

    App.prototype.render = function(e) {
      var bmp;
      bmp = board2bitmap(this.board);
      return bmp.render(e, bmp);
    };

    return App;

  })();

  main = function() {
    var app, canvas, f, timerId;
    app = new App;
    canvas = document.getElementById('canvas');
    f = function() {
      app.render(canvas);
      return app.next();
    };
    return timerId = setInterval(f, 300);
  };

  main();

}).call(this);
