// Generated by CoffeeScript 1.8.0
(function() {
  var board2bitmap, main, new_canvas;

  board2bitmap = function(board) {
    var bmp, _i, _ref, _results;
    bmp = new Window.Bitmap(board.width, board.height);
    (function() {
      _results = [];
      for (var _i = 0, _ref = board.height - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).map(function(j) {
      var _i, _ref, _results;
      return (function() {
        _results = [];
        for (var _i = 0, _ref = board.width - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this).map(function(i) {
        var c;
        c = bmp.pixel(0xff, (board.bitmap[j][i] ? 0x00 : 0xf3), 0xff);
        return bmp.set(i, j, c);
      });
    });
    return bmp.bold(5);
  };

  new_canvas = function() {
    var c;
    c = document.createElement('canvas');
    document.body.appendChild(c);
    document.body.appendChild(document.createElement('br'));
    return c;
  };

  main = function() {
    var c, f, g;
    c = new_canvas();
    g = new Window.Game(12, 15);
    document.onkeydown = function(e) {
      return g.key(e.keyCode);
    };
    g.render = function() {
      return board2bitmap(g).render(c);
    };
    f = function() {
      g.next();
      return g.render();
    };
    return setInterval(f, 300);
  };

  main();

}).call(this);
